---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-ca
  namespace: openshift-config
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEUzCCArugAwIBAgIQHvp3CiQAppF8xkhD2m4xeDANBgkqhkiG9w0BAQsFADAz
    MREwDwYDVQQKDAhDTEFNLkxBTjEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9y
    aXR5MB4XDTI2MDQyNzEzMTU1OVoXDTQ2MDQyNzEzMTU1OVowMzERMA8GA1UECgwI
    Q0xBTS5MQU4xHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTCCAaIwDQYJ
    KoZIhvcNAQEBBQADggGPADCCAYoCggGBAMGLjANd2r4zJ8F0UPdrgrds4YTRwqCL
    dcwysxjnUb3yJHwBVstY8kHfumKXHGIyoSUsZcbh32j71ZDp2Gg8kcIyE35Vs3WC
    0gbsTj4iggl30KTAy0ycdtU41n6rBki0p1js7RL9ZMMCAbJKxbWGTqfYm3Qq6s2A
    2p8c/7Dcq3FH4nZg1tzyQHZJm4hW3acN/ThXNpFSbf2mnV7uCYfymKXuqs4ZAifD
    KEtaNf4k5ROk0YX34kHSxyMQNircoTO4CSgXJEKcTEUtcFQLrZi+NCu6L1lO22Vs
    Hip2fxLEjoCT9NcrUXbUeNXOv4ixaTKNiq5NGh4FJ5k0cKTV4/y4IP0m34sgA/V+
    Gaw6a8WjmLDK9Rpxd2/Rb91Zh6jSUzC2geMrZBEvOe9q0uGzmw6LKUWjps4HHEHL
    N/6QhHxogXnBDKLa5uVIjsj35P/C+alA8/aS9dBqGQGZwDLd90ABm1kpP5O9foVB
    Ahj67vctts7bPjarvkebdobu7Gf10r9yewIDAQABo2MwYTAdBgNVHQ4EFgQUGJAJ
    hvfyWGzNluR8DgGV0zhsmzwwHwYDVR0jBBgwFoAUGJAJhvfyWGzNluR8DgGV0zhs
    mzwwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAcYwDQYJKoZIhvcNAQEL
    BQADggGBADWzwZ1ltD+d6kBmz/hWu4PlTHlyBKacgvDct2sbKT0N/VHAnJsbNCzh
    XdpXlRZSurKKhJeOYzbL7tjkbYK2ZwcUJaWrYiQpEj0xwQJyzufAa8pynJ8SnMQi
    0dND1NkRnFzgeUB951R2eJxZUmWQ8oEVSaK1m5Ha9rQf3GJjoER6uGnHZ98nf0Pg
    qmehUW3KMCa8P7wix9VbATpUILdflINDeDgWrebLwJFZB+yT/3MPQMIEJngj4gIT
    Vfh6DTnew77+xQ/bC++h75dZ5ecCbE5/fSkzuUkpd4+5J+DtUD7zKFo58JEIoeTj
    sXHnsGnbpkDOsB7snRvkTxCArtw6dO5zO36dzsZIc1u7QpWgoTuwZtVxqjTlG1zN
    gwCGsqL1KGyUDzGJo/9s9fMH6JzTB8C3QJ0qL6Wav6sujhUmQ8j0reMOgcs4+XAL
    ahq+XogBegIgUteSDCjB5gcDJhv2Ldmw+zGUVEi0yUjXiM4vSTFvNbsa2KqFeMEq
    f5FrZQ7IsA==
    -----END CERTIFICATE-----
