---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-ca
  namespace: openshift-config
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIEVTCCAr2gAwIBAgIQMMQBW5dD6VoaD/o30CVAfzANBgkqhkiG9w0BAQsFADA0
    MRIwEAYDVQQKDAlDTEFNSUUuQVUxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhv
    cml0eTAeFw0yNjA1MDkwNzEyMTlaFw00NjA1MDkwNzEyMTlaMDQxEjAQBgNVBAoM
    CUNMQU1JRS5BVTEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBojAN
    BgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAu7IaMW8tJaxoWj7cWDyqffFiRlwi
    0xLvLfYnWozyzkF7P5ODGc005se+Pz1cCB/ex4X4gX1AH+nKk5pAub85AiWcNreD
    aqg1owLsaTQRK7JAegL4vAJJ+cW9oLu1h9yKe9PFDOxjHz6So05h94T6m0bP36DK
    ZLcHKdddnms0bzY1vbe8i7S72igjYA6CNqa/lmH6SV4x0Rqak4Z1wtnhYwczlAj1
    LQwnrdS3xFT6RpjQibou1B5Bhfxiflur0oPs7HM3PzS6c6CSaVm31VhE954Z6+xL
    Nj+XkLWKRGGQU30mh2D+trzfehm6qY+KVr/6GzjYmk8ga6GlpGHa+3Q445v5hLir
    NINUrYjkpg5KNSx8kleVLgD2G5YWkwjpHcXWdAUnQP38VoP8VcicbIHCwc8BEuo9
    z+tT6MQZWbiBudLqo48yh+n/YIQSTGcEzPhk4j2ObUAqllvA0bIN0wXf2pLALP74
    5BJfm5JbNN247YbSeoyMYDw1OKMNTC1kU0wnAgMBAAGjYzBhMB0GA1UdDgQWBBSp
    qfW1Ur4APz8/zu7jhyol89h+ajAfBgNVHSMEGDAWgBSpqfW1Ur4APz8/zu7jhyol
    89h+ajAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBxjANBgkqhkiG9w0B
    AQsFAAOCAYEASrGFbkweA1qgKl1o/arBweorlV2o7gboK8tNBQg8QIt4bLm6EVGA
    LX3yVdE2WBLi2alKu65A4iJWWWplz3R7eBL25RblrhMoKjSzW/5aj9fPJJMU37Go
    rJjzi0oYKktITeJVFPC7JI/Fm0dgzhft/6N+4UGM4s/qrB/R3fjibpbG/gr1NU0f
    801uaDD/QT4Wa7wnDBsBgRrv0kAbCZer032kY6bGbXmohgeGfq1R1jAWjXoQ5KOM
    4vOpnK6uY3mb/71+o5n00sgMbH5rGQYth4hUacUog6YVI1CDG63eBxPPaVwaFtZw
    Br1TC46mF1gfXJRxGb6hmvowRyARHqR9Jzhxqk8jR96FmSfUUdhhyS8SxPl9V+WJ
    iuwtCGRDd0wMqyMAsG5inuxw3vumP1PdnnyzsDUg1Wd4doLi94L1hTDq4bylkOPU
    QuLnQeUApslM5m1GhO06e+KC7bACJtUJBcAuzpgchRhnmt7vIBhs9c9UAcRts4WS
    QkvwWjzsVHeG
    -----END CERTIFICATE-----